kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: challenge-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      - containerPort: 30566
        hostPort: 4566
        protocol: TCP
      - containerPort: 31433
        hostPort: 1433
        protocol: TCP

